services:
  api1:
    image: ghcr.io/fksegundo/rinha-dotnet:latest
    pull_policy: always
    restart: always
    logging:
      driver: "none"
    environment:
      RINHA_FD_SOCKET: /sockets/api1.sock
      RINHA_INDEX_PATH: /app/index/rinha-specialist.idx
      RINHA_RUNTIME: event-loop
      RINHA_WARMUP_QUERIES: "64"
      RINHA_SEARCH_MODE: key-first
      RINHA_THREAD_POOL_SIZE: "256"
      RINHA_MLOCK_ALL: "1"
      RINHA_MLOCK_INDEX: "1"
      RINHA_MLOCK_ALL_MODE: future
      DOTNET_gcServer: "0"
      MALLOC_ARENA_MAX: "2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "167M"

  api2:
    image: ghcr.io/fksegundo/rinha-dotnet:latest
    pull_policy: always
    restart: always
    network_mode: "none"
    logging:
      driver: "none"
    environment:
      RINHA_FD_SOCKET: /sockets/api2.sock
      RINHA_INDEX_PATH: /app/index/rinha-specialist.idx
      RINHA_RUNTIME: event-loop
      RINHA_WARMUP_QUERIES: "64"
      RINHA_SEARCH_MODE: key-first
      RINHA_THREAD_POOL_SIZE: "256"
      RINHA_MLOCK_ALL: "1"
      RINHA_MLOCK_INDEX: "1"
      RINHA_MLOCK_ALL_MODE: future
      DOTNET_gcServer: "0"
      MALLOC_ARENA_MAX: "2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "167M"

  lb:
    image: ghcr.io/fksegundo/rinha-dotnet-lb:latest
    pull_policy: always
    restart: always
    user: "0:0"
    ports:
      - "9999:9999"
    logging:
      driver: "none"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "16M"
    depends_on:
      - api1
      - api2

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
