services:
  api1:
    image: rinha-dotnet-aot-api:local
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        RINHA_LEAF_SIZE: ${RINHA_LEAF_SIZE:-48}
    pull_policy: never
    restart: always
    logging:
      driver: "none"
    environment:
      RINHA_UDS_SOCKET: /sockets/api1.sock
      RINHA_INDEX_PATH: /app/index/rinha-specialist.idx
      RINHA_WARMUP_QUERIES: "${RINHA_WARMUP_QUERIES:-64}"
      RINHA_SEARCH_MODE: key-first
      DOTNET_ThreadPool_MinThreads: "${DOTNET_ThreadPool_MinThreads:-16}"
      DOTNET_gcServer: "0"
      MALLOC_ARENA_MAX: "2"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

  api2:
    image: rinha-dotnet-aot-api:local
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        RINHA_LEAF_SIZE: ${RINHA_LEAF_SIZE:-48}
    pull_policy: never
    restart: always
    logging:
      driver: "none"
    environment:
      RINHA_UDS_SOCKET: /sockets/api2.sock
      RINHA_INDEX_PATH: /app/index/rinha-specialist.idx
      RINHA_WARMUP_QUERIES: "${RINHA_WARMUP_QUERIES:-64}"
      RINHA_SEARCH_MODE: key-first
      DOTNET_ThreadPool_MinThreads: "${DOTNET_ThreadPool_MinThreads:-16}"
      DOTNET_gcServer: "0"
      MALLOC_ARENA_MAX: "2"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165M"

  lb:
    image: ${LB_IMAGE:-haproxy:3.0.9-alpine}
    restart: always
    ports:
      - "9999:9999"
    logging:
      driver: "none"
    volumes:
      - ${PROXY_CONFIG_HOST:-./haproxy.cfg}:${PROXY_CONFIG_CONTAINER:-/usr/local/etc/haproxy/haproxy.cfg}:ro
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20M"
    depends_on:
      - api1
      - api2

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m
