FROM rust:1.87-slim-bookworm AS builder

ARG RUST_TARGET_CPU=haswell
ENV RUSTFLAGS="-C target-cpu=${RUST_TARGET_CPU} -C target-feature=+avx2,+fma,+popcnt,+sse4.2 -C opt-level=3 -C panic=abort -C link-arg=-Wl,--gc-sections -C link-arg=-Wl,-O1"

WORKDIR /lb
COPY src/lb/Cargo.toml ./
COPY src/lb/src ./src/

RUN cargo build --release

FROM gcr.io/distroless/cc
COPY --from=builder /lb/target/release/rinhaLb /usr/local/bin/lb
ENTRYPOINT ["/usr/local/bin/lb"]
